qemu: fix TOLUD for PCI passthrough
QubesOS/qubes-vmm-xen-stubdom-linux pull request #44
Opened 2022-03-27 16:41 UTC by mati7337

By default qemu sets the top of low usable DRAM to 3.75G which isn't
enough for larger BARs in most GPUs. hvmloader seems to try relocating
memory which overlaps with PCI addresses, but for some reason it doesn't
work. Too low TOLUD also causes problems as VMs crash while starting with
logs indicating a problem with qemu's emulated ehci hc.

This patch solves this problem by setting TOLUD to accomodate the lowest
address of a PCI device attached to the stubdomain.

fixes QubesOS/qubes-issues#4321

2022-03-28 17:12 UTC, marmarek requested changes

2022-03-28 17:12 UTC, marmarek commented on qemu/patches/Fix-TOLUD-for-PCI-passthroughed-devices.patch
> ++    sscanf(line, "%llx-%llx : %lln", &entry->addr_start, &entry->addr_end, &pos);
check return value

2022-03-28 17:12 UTC, marmarek commented on qemu/patches/Fix-TOLUD-for-PCI-passthroughed-devices.patch
> ++    sscanf(line+pos, "%*s%lln\n", &entry->name_len);
here too

2022-03-28 17:12 UTC, marmarek commented on qemu/patches/Fix-TOLUD-for-PCI-passthroughed-devices.patch
> ++        sscanf(entry.name, "%*llx:%*llx:%*llx.%*llx%lln", &chars_match);
check return value

2022-03-28 17:12 UTC, marmarek commented on qemu/patches/Fix-TOLUD-for-PCI-passthroughed-devices.patch
> ++    FILE* iomem = fopen("/proc/iomem", "r");
and here

2022-03-28 17:12 UTC, marmarek commented on qemu/patches/Fix-TOLUD-for-PCI-passthroughed-devices.patch
> ++    char *iomem_line = (char *)malloc(iomem_line_bufsize * sizeof(char));
and here

2022-03-28 17:12 UTC, marmarek commented on qemu/patches/Fix-TOLUD-for-PCI-passthroughed-devices.patch
> ++        if (entry.name == 0) {
You need to initialize `entry` above to rely on this. But better make `parse_iomem_entry` return success/failure explicitly and use that.

2022-04-06 03:34 UTC, marmarek approved these changes

2022-04-06 03:35 UTC, merged

2023-08-07 12:11 UTC, IOZZYS commented
Still requires manual patch in Qubes 4.2 https://github.com/QubesOS/qubes-issues/issues/4321#issuecomment-1551203532